# TF-A-N Default Configuration
# All hard gates and thresholds are set to specification values

# Model architecture
d_model: 768
n_heads: 12
n_layers: 12
d_ff: 3072
dropout: 0.1
max_seq_len: 32768

# Training
batch_size: 8
gradient_accumulation_steps: 4
base_lr: 0.0003
base_temperature: 1.0
warmup_steps: 1000
max_steps: 100000
eval_interval: 500
save_interval: 2000

# Hardware
device: "cuda"
mixed_precision: true
compile_model: false

# Trainable Time Warping
ttw:
  max_iter: 50
  p95_latency_ms: 5.0
  coverage_target: 0.9
  trigger_vfe_spike_threshold: 0.15
  trigger_entropy_jump_threshold: 0.25
  auroc_threshold: 0.8

# Sparse Attention & TLS
attention:
  keep_ratio: 0.33
  alpha: 0.7
  window_size: 128
  per_head_masks: true
  degree_floor: 2
  speedup_target: 3.0
  accuracy_delta_max: 0.02
  mask_value: -10000.0
  enable_cat_fallback: true
  cat_fallback_ratio: 0.5

# Topological Regularization
topology:
  lambda_topo: 0.01
  filtration_type: "rips"
  homology_degrees: [0, 1]
  landscape_levels: 5
  wasserstein_gap_max: 0.02
  cosine_min: 0.9
  enable_nightly_exact: true
  nightly_max_samples: 5000
  nightly_timeout_min: 20

# Memory Scaling
memory:
  alpha_max: 1.0
  test_sequence_lengths: [1024, 2048, 4096, 8192, 16384, 32768]

# Hyperbolic Geometry
hyperbolic:
  enable: true
  manifold: "poincare"
  tree_likeness_threshold: 0.6
  ndcg_improvement_target: 0.05
  overhead_max: 0.12

# FDT Homeostat
fdt:
  kp: 0.3
  ki: 0.02
  kd: 0.1
  ema_alpha: 0.95
  grad_clip_norm: 1.0
  epr_cv_max: 0.15
  temperature_min: 0.5
  temperature_max: 2.0
  lr_min: 0.000001
  lr_max: 0.01

# Emotion
emotion:
  mode: "VA"
  loss_type: "CCC"
  temporal_smoothness_weight: 0.1
  enable_topo_trajectory: true
  topo_trajectory_beta0_target: 1
  topo_trajectory_beta1_target: 0
  arousal_temp_coupling: [0.8, 1.3]
  valence_lr_coupling: [0.7, 1.2]
  controller_weight: 0.3
  jerk_threshold: 0.1
  confidence_threshold: 0.5

# Proof-Gated Updater
pgu:
  timeout_ms: 120
  fallback_timeout_ms: 180
  p95_latency_max_ms: 200.0
  cache_size: 10000
  cache_cycle_batches: 1000
  cache_hit_target: 0.5
  rule_cap: 20
  mode: "soft"
  safety_domain_hard_mode: true

# Multi-Modal
multimodal:
  modalities: ["text", "audio", "video"]
  audio_sample_rate: 16000
  audio_n_mels: 80
  audio_hop_length: 160
  video_fps: 30
  video_patch_size: 16
  video_backbone: "vit_base_patch16_224"
  packing_order: ["text", "audio", "video"]
  late_stream_degradation: 0.5

# Pareto Optimization
pareto:
  algorithm: "EHVI"
  objectives: ["accuracy", "latency", "epr_cv", "topo_gap", "energy"]
  n_iterations: 50
  population_size: 24
  min_non_dominated: 6

# Monitoring
monitoring:
  enable_prometheus: true
  prometheus_port: 9090
  scrape_interval_sec: 30
  enable_grafana: true
  grafana_port: 3000
  enable_wandb: false
  wandb_project: null

# Artifacts
artifact_dir: "./artifacts"
checkpoint_dir: "./checkpoints"
log_dir: "./logs"
